### ISSUE TITLE
Allow users to import any additional voxel-wise feature map in addition to basic/TomoTwin features 

### ISSUE THREAD

**Issue by uermel** [kephale/cryocanvas#3]
Thinking about outputs from TomoSegMemTV for example, or the embedding of any other network people may have already trained. Even template matching probability maps may be something people may want to import.

**Comment by kephale** [comment]
One related point (not a counter argument): for the UX evaluation we're getting ready for the test zarrs contain precomputed features (esp because TomoTwin is slow to compute). 

The point being that this feature might come after the UX eval.

**Comment by uermel** [comment]
I see. I do think especially for membrane proteins it would be really beneficial to have the ability to import membrane features from dedicated membrane prediction tools, be it predictions from TomoSegMem, MembrainSeg or TARDIS.
